---
- name: "Enable service nginx"
  become: true
  ansible.builtin.systemd:
    name: nginx
    enabled: true

- name: "Started service nginx"
  become: true
  ansible.builtin.systemd:
    name: nginx
    state: started
