---
dependency:
  name: galaxy

driver:
  name: vagrant
  provider:
    name: virtualbox

platforms:
  - name: centos
    box: centos/7
    memory: 1024
    cpus: 1

provisioner:
  name: ansible

verifier:
  name: ansible
